#tmux attach &> /dev/null || tmux &> /dev/null
 #tmux attach &> /dev/null 
 #if [[ ! $TERM =~ screen ]]; then; exec tmux; fi
autoload -Uz compinit
compinit

source ~/dotfiles/zsh/setopt.zsh

source ~/dotfiles/zsh/exports.zsh

source ~/dotfiles/zsh/history.zsh

source ~/dotfiles/zsh/colors.zsh

source ~/dotfiles/zsh/prompt.zsh

source ~/dotfiles/zsh/plugins_config.zsh

[ -f ~/.profile  ] && source ~/.profile

source ~/dotfiles/zsh/aliases.zsh

source ~/dotfiles/zsh/keybindings.zsh

# zsh: Place this in .zshrc after "source /Users/georgen/.iterm2_shell_integration.zsh".
iterm2_print_user_vars() {
  iterm2_set_user_var neovim_tabcount $(launchctl getenv neovim_tabcount)
}
